# References below:
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://github.com/alexleventer/github-issue-due-dates-action

name: Main Workflow
on:
  schedule:
    - cron:  '0 * * * *'
jobs:
  Ubuntu:
    name: Add labels to issues
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Issue Due Dates Action
        uses: alexleventer/github-issue-due-dates-action@1.0.12
        with:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
